### ISSUE TITLE
Error when trying to install NXP::EVK-MIMXRT1064_BSP@14.0.0 with cpackget 2.1.1  

### ISSUE THREAD

**Issue by mguzmanm** [Open-CMSIS-Pack/cpackget#282] opened 2024-04-09 11:00 UTC
**Describe the bug**

Installation of pack NXP::EVK-MIMXRT1064_BSP@14.0.0 was locally tested in Windows and Linux with CMSIS-Toolbox 2.3.0 which includes cpackget [Package Installer 2.1.1](https://github.com/Open-CMSIS-Pack/cpackget/releases/tag/v2.1.1) and with CMSIS-Toolbox 2.2.1 wich includes cpackget [Package Installer 2.0.0](https://github.com/Open-CMSIS-Pack/cpackget/releases/tag/v2.0.0)

` ./cpackget.exe add NXP::EVK-MIMXRT1064_BSP@14.0.0`

Results showed that the pack can be installed with cpackget 2.0.0. However, the same pack can not be installed with cpackget 2.1.1

**To Reproduce**
1. Remove or rename the packs "EVK-MIMXRT1064_BSP" and "MIMXRT1064_DFP" from packs folder e.g.: C:\Users\youruser\AppData\Local\Arm\Packs\NXP
2. Run cpackget 2.1.1 with the following args:
` ./cpackget.exe add NXP::EVK-MIMXRT1064_BSP@14.0.0`
4. See error:

> I: Extracting files to C:\Users\youuser\AppData\Local\Arm\Packs\NXP\EVK-MIMXRT1064_BSP\14.0.0...
> I: Package requirements not satisfied - installing NXP::MIMXRT1064_DFP@>=14.0.0
> W: Could not resolve version modifier
> I: Downloading NXP.MIMXRT1064_DFP.18.0.0.pack...
> 
> I: Adding pack NXP.MIMXRT1064_DFP.
> E: The latest release (18.0.0) in pack's pdsc (NXP.MIMXRT1064_DFP.pdsc) does not match pack version ""
> E: pack version is not the latest in the pdsc file

**Expected behavior**
Pack NXP::EVK-MIMXRT1064_BSP@14.0.0 should be succesfully installed as it does with cpackget 2.0.0

**Environment (please complete the following information):**
 - OS: Windows and Linux
 - Version 2.1.1

**Comment by edriouk** [comment] 2024-04-10 16:10
duplicate of https://github.com/Open-CMSIS-Pack/cpackget/issues/283

**Closed by edriouk** 2024-04-10 16:10 UTC
